include ../common_pre.mk

OBJPATH = ${BUILDPATH}/cli
RESULT = ${BUILDPATH}/paysages-cli
SOURCES += $(wildcard *.c)
HEADERS += $(wildcard *.h)

CC_LDFLAGS += -L${BUILDPATH} -lpaysages

include ../common_post.mk
